config/routes.rb
App::Application.routes.draw do
  resources :acts
  resources :amoebas
  match 'amoebas/split/:baby_maker' => 'amoebas#split'
  get 'talents' => 'talents#index'
  get 'talents/:id' => 'talents#show'

end

app/models/act.rb
class Act < ActiveRecord::Base
  attr_accessible :name, :date_time
  has_many :amoebas
  has_many :talents, through: :amoebas
end

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
  attr_accessible :name, :act_id, :talent_id, :gen_num
  belongs_to :act
  has_one :talent

  NAMES = ["Confeedent", "Steady Hands", "Clumsee", "Skared", "Crush",
    "Crazee", "InLove", "Beyonce", "Blake", "Bulake"]

  def split
    babies = []
    babies << Amoeba.create(:name => NAMES.sample, :act_id => act_id, 
      :talent_id => talent_id, :gen_num => gen_num + 1)
    babies << Amoeba.create(:name => NAMES.sample, :act_id => act_id, 
      :talent_id => talent_id, :gen_num => gen_num + 1)
    destroy
    babies
  end

end

app/models/talent.rb
class Talent < ActiveRecord::Base
  attr_accessible :name
  has_many :amoebas
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  def index
    @acts = Act.all
  end

  def show
    @act = Act.find(params[:id])
  end

  def new
    @act = Act.new
  end

  def create
    @act = Act.new(params[:act])
    if @act.save
      redirect_to @act
    end
  end

end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController
  def index
    @amoebas = Amoeba.all
  end

  def show
    @amoeba = Amoeba.find(params[:id])
  end

  def new
    @amoeba = Amoeba.new
  end

  def create
    @amoeba = Amoeba.new(params[:amoeba])
    if @amoeba.save
      redirect_to @amoeba
    end
  end

  def split
    amoeba = Amoeba.find(params[:baby_maker])
    @split_amoeba = amoeba.split
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  def index
    @talents = Talent.all
  end

  def show
    @talent = Talent.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts/index.html.haml
%h1 All the Acts

%table
  %tr
    %th Name

  - @acts.each do |act|
    %tr
      %td= act.name
      %td= link_to 'Show', act

%br

= link_to 'New Act', new_act_path

app/views/acts/new.html.haml
%h1 New Act

= render 'form'

= link_to 'Back', acts_path

app/views/acts/show.html.haml
%h1= @act.name

%p
  %b Date and Time of performance:
  = @act.date_time
%p
  %b Performers:
  %br
  - @act.amoebas.each do |amoeba|
    = link_to "#{amoeba.name}", amoeba
    %br


.btn= link_to 'All Acts', acts_path

app/views/amoebas/_form.html.haml
= form_for @amoeba do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :act_id
    = f.number_field :act_id
  .field
    = f.label :talent_id
    = f.number_field :talent_id
  .actions
    = f.submit 'Birth It'

app/views/amoebas/index.html.haml
%h1 All the Amoebas

%table
  %tr
    %th Name
    %th Act
    %th Talent
    %th Generation

  - @amoebas.each do |amoeba|
    %tr
      %td= link_to "#{amoeba.name}", amoeba
      %td= link_to "#{Act.find(amoeba.act_id).name}", "acts/#{amoeba.act_id}"
      %td= link_to "#{Talent.find(amoeba.talent_id).name}", "talents/#{amoeba.talent_id}"
      %td= amoeba.gen_num
      %td= button_to 'Split', "/amoebas/split/#{amoeba.id}", :method => :split, :data => { :confirm => 'You sure?'}

%br

= button_to 'New Amoeba', new_amoeba_path

app/views/amoebas/new.html.haml
%h1 New Amoeba

= render 'form'

= link_to 'Back', amoebas_path

app/views/amoebas/show.html.haml
%h1= @amoeba.name

%p
  %b Act:
  = link_to Act.find(@amoeba.act_id).name, "/acts/#{@amoeba.act_id}"
%p
  %b Talent:
  = link_to Talent.find(@amoeba.talent_id).name, "/talents/#{@amoeba.talent_id}"
%p
  %b Generation:
  = @amoeba.gen_num

= button_to 'Split Amoeba', "/amoebas/split/#{@amoeba.id}", :method => :split, :data => { :confirm => 'You sure?' }
.btn= link_to 'All Amoebas', amoebas_path

app/views/amoebas/split.html.haml
%h1 The Amoeba you split is now dead.
%h2 But two more were born in its place.

%table
  %tr
    %th Name
    %th Act
    %th Talent
    %th Generation

- @split_amoeba.each do |baby|
  %tr
    %td= link_to baby.name, baby
    %td= link_to Act.find(baby.act_id).name, "/acts/#{baby.act_id}"
    %td= link_to Talent.find(baby.talent_id).name, "/talents/#{baby.talent_id}"
    %td= baby.gen_num
  %br

%br

.btn= link_to 'All Amoebas', amoebas_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <link rel="stylesheet" type="text/css" href="/bootstrap/css/bootstrap.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="/amoebas">Amoeba Circus</a>
      <ul class="nav">
        <li class="active">
          <a href="/amoebas">Amoebas</a>
        </li>
        <li>
          <a href="/acts">Acts</a>
        </li>
        <li>
          <a href="/talents">Talents</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="http://code.jquery.com/jquery.js"></script>
  <script src="/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

app/views/talents/_form.html.haml
= form_for @act do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :date_time
    = f.text_field :date_time
  .actions
    = f.submit 'Make It'

app/views/talents/index.html.haml
%h1 All the Talents

%table
  %tr

  - @talents.each do |talent|
    %tr
      %td= talent.name
      %td= link_to 'Show', "/talents/#{talent.id}"

%br

.btn= link_to "All Amoebas", amoebas_path

app/views/talents/show.html.haml
%h1= @talent.name

%b Amoebas with this talent:
%p
  - @talent.amoebas.each do |amoeba|
    %p= link_to "#{amoeba.name}", amoeba

.btn= link_to 'All Talents', talents_path
.btn= link_to 'All Amoebas', amoebas_path